create table if not exists public.player_record_snapshots (
  id bigint generated by default as identity primary key,
  player_id text not null,
  player_name text not null,
  team_code text not null,
  role text not null check (role in ('타자', '투수')),
  as_of_date date not null,
  career_stats jsonb not null default '{}'::jsonb,
  season_stats jsonb not null default '{}'::jsonb,
  source_url text not null,
  fetched_at timestamptz not null default now(),
  unique (player_id, role, as_of_date)
);

create table if not exists public.milestone_candidates (
  id text primary key,
  player_id text not null,
  player_name text not null,
  team_code text not null,
  role text not null check (role in ('타자', '투수')),
  stat_key text not null,
  as_of_date date not null,
  active_from date not null,
  active_to date not null,
  milestone numeric not null,
  current_value numeric not null,
  remaining numeric generated always as (greatest(milestone - current_value, 0)) stored,
  current_text text,
  remaining_text text,
  unit text not null,
  title text not null,
  recent jsonb not null default '[0,0,0,0,0]'::jsonb,
  season jsonb not null default '{}'::jsonb,
  note text not null default '',
  source_url text not null,
  source_type text not null default 'calculated',
  updated_at timestamptz not null default now(),
  unique (player_id, role, stat_key, milestone, as_of_date)
);

create table if not exists public.record_sync_runs (
  id bigint generated by default as identity primary key,
  sync_date date not null,
  status text not null check (status in ('running', 'success', 'failed')),
  player_count integer not null default 0,
  candidate_count integer not null default 0,
  message text not null default '',
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists milestone_candidates_active_dates_idx
  on public.milestone_candidates (active_from, active_to);

create index if not exists milestone_candidates_team_idx
  on public.milestone_candidates (team_code, remaining);

alter table public.player_record_snapshots enable row level security;
alter table public.milestone_candidates enable row level security;
alter table public.record_sync_runs enable row level security;

drop policy if exists "Public can read calculated milestone candidates" on public.milestone_candidates;
create policy "Public can read calculated milestone candidates"
  on public.milestone_candidates
  for select
  to anon, authenticated
  using (source_type = 'calculated');

grant usage on schema public to anon, authenticated;
grant select on public.milestone_candidates to anon, authenticated;

comment on table public.player_record_snapshots is 'KBO 선수 페이지에서 수집한 날짜별 통산 및 시즌 스냅숏';
comment on table public.milestone_candidates is '스냅숏에서 자체 규칙으로 계산한 달성 임박 기록';
comment on table public.record_sync_runs is '자동 수집 실행 이력';
